import pandas as pd
import polars as pl
import numpy as np

# Mock functions to simulate the environment
def progress(n):
    print(f"Progress: {n}%")

def show_result(title, result):
    print(f"\n--- {title} ---")
    if isinstance(result, pd.DataFrame):
        print(result.to_string())
    else:
        # For correlation, it's HTML, just print a snippet
        print(result[:500] + "...")

# Case 1: Constant Column (Std Dev/Var/Correlation issues)
df_constant = pd.DataFrame({
    "Const": [1, 1, 1, 1],
    "Normal": [1, 2, 3, 4]
})

# Case 2: All Null Column
df_null = pd.DataFrame({
    "Nulls": [None, None, None, None],
    "Normal": [1, 2, 3, 4]
})

# Case 3: Mixed Data (Strings in Numeric)
df_mixed = pd.DataFrame({
    "Mixed": [1, "A", 3, 4],
    "Normal": [1, 2, 3, 4]
})

# Case 4: Empty DataFrame
df_empty = pd.DataFrame(columns=["A", "B"])

def test_descriptive(df_test, title):
    print(f"\nTesting Descriptive: {title}")
    vars_to_analyze = list(df_test.columns)
    
    # Simulate the code generated by DescriptiveStatsDialog (Polars branch)
    try:
        df = pl.from_pandas(df_test)
        stats_list = []
        for i, col in enumerate(vars_to_analyze):
            s = df.get_column(col)
            is_num = s.dtype.is_numeric()
            if is_num:
                row = {
                    'Variable': col,
                    'Count': s.len() - s.null_count(),
                    'Type': 'Numeric',
                    'Mean': s.mean(),
                    'Median': s.median(),
                    'Mode': s.mode().get(0) if len(s.mode()) > 0 else None,
                    'Min': s.min(),
                    'Max': s.max(),
                    'Std Dev': s.std(),
                    'Variance': s.var(),
                    '25th %ile': s.quantile(0.25),
                    '75th %ile': s.quantile(0.75),
                    'Unique Values': None
                }
            else:
                row = {
                    'Variable': col,
                    'Count': s.len() - s.null_count(),
                    'Type': 'Categorical',
                    'Mean': None, 'Median': None,
                    'Mode': s.mode().get(0) if len(s.mode()) > 0 else None,
                    'Min': None, 'Max': None, 'Std Dev': None, 'Variance': None,
                    '25th %ile': None, '75th %ile': None,
                    'Unique Values': s.n_unique()
                }
            stats_list.append(row)
        results_df = pd.DataFrame(stats_list)
        show_result('Descriptive Statistics', results_df)
    except Exception as e:
        print(f"Descriptive Error ({title}): {e}")

def test_correlation(df_test, title):
    print(f"\nTesting Correlation: {title}")
    cols = list(df_test.columns)
    method = 'pearson'
    
    try:
        # Filter only numeric for correlation as intended
        numeric_cols = [c for c in cols if pd.api.types.is_numeric_dtype(df_test[c])]
        if len(numeric_cols) < 2:
            print(f"Skipping Correlation ({title}): Less than 2 numeric columns")
            return
            
        df = pl.from_pandas(df_test[numeric_cols])
        sub = df.select(numeric_cols).drop_nulls().to_pandas()
        
        if len(sub) == 0:
            print(f"Correlation Error ({title}): No data after dropping nulls")
            return

        corr = sub.corr(method=method)
        n = len(sub)
        
        # Heatmap simulation (Simplified)
        import matplotlib.pyplot as plt
        import seaborn as sns
        fig, ax = plt.subplots()
        sns.heatmap(corr, annot=True, ax=ax)
        plt.close(fig)
        
        print(f"Correlation Success ({title})")
        print(corr.to_string())
    except Exception as e:
        print(f"Correlation Error ({title}): {e}")

test_descriptive(df_constant, "Constant")
test_descriptive(df_null, "Nulls")
test_descriptive(df_mixed, "Mixed")
test_descriptive(df_empty, "Empty")

test_correlation(df_constant, "Constant")
test_correlation(df_null, "Nulls")
test_correlation(df_mixed, "Mixed")
test_correlation(df_empty, "Empty")
